import { StyleSheet } from "react-native";
import { colors } from "../../utils";
import { RfH, RfW } from "../../utils/helper";

export default styles = StyleSheet.create({
  container: {
    backgroundColor: colors.WHITE,
  },
  homecontainer: {},
  imgcontainer: {
    backgroundColor: colors.GRAY,
    height: RfH(32),
    width: RfW(32),
    borderRadius: RfH(16),
    justifyContent: "center",
  },
  postcontainer: {
    flexDirection: "row",
  },
  separator: {
    borderBottomWidth: 1,
    borderColor: colors.GRAY,
    // marginHorizontal: RfW(20),
    marginVertical: RfH(5),
  },
  namesty: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.black,
    paddingHorizontal: RfW(10),
    lineHeight: RfH(17),
    fontFamily: "Poppins-Medium",
  },
  noPostText: {
    color: colors.black,
  },
  timesty: {
    fontSize: 11,
    fontWeight: "400",
    color: colors.DARK_GRAY,
    paddingHorizontal: RfW(10),
    lineHeight: RfH(14),
    fontFamily: "Poppins-Medium",
  },
  followcontainer: { flexDirection: "row" },
  followBtn: {
    width: RfW(77),
    height: RfH(22),
    borderWidth: 1,
    borderColor: colors.black,
    borderRadius: RfH(7),
    justifyContent: "center",
    marginHorizontal: RfW(20),
    marginTop: RfH(2),
  },
  followedBtn: {
    backgroundColor: colors.skyblue,
    borderColor: "#7966FF",
  },
  followtxt: {
    alignSelf: "center",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.black,
    fontFamily: "Poppins-Regular",
    top: RfH(1),
  },
  msgtextsty: {
    marginTop: RfH(10),
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.black,
    fontFamily: "Poppins-Regular",
    left: RfW(2),
  },
  massagepostcontainer: {
    borderWidth: 1,
    // padding: RfH(10),
    borderRadius: RfH(7),
    borderColor: colors.LIGHT_BLACK,
    marginVertical: RfH(8),
    width: RfW(337),
    alignSelf: "center",
  },
  othercontainer: { flexDirection: "row", paddingBottom: RfH(10) },
  postimgsty: {
    width: "100%",
    height: "100%",
    borderRadius: RfH(8),
    marginVertical: RfH(10),
    alignSelf: "center",
    resizeMode: "contain",
  },

  // Video hbhabha
  tabVideo: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    paddingLeft: RfW(85),
    backgroundColor: "red",
    width: RfW(307),
    backgroundColor: colors.shadwo_blue,
    borderRadius: RfH(8),
    marginTop: RfH(10),
  },
  playButton: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  clearButton: {
    // position: 'absolute',
    // marginLeft: '37%',
    // marginTop: '16%',
  },
  video: {
    alignSelf: "center",
    width: RfW(340),
    height: RfH(350),
    // borderRadius:7
    // borderRadius: RfH(8),
    // paddingVertical: RfH(10),
    // marginTop: RfH(10),
    // resizeMode:'',
  },

  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  homecontainer: { marginTop: RfH(20) },
  imgcontainer: {
    backgroundColor: colors.GRAY,
    height: RfH(32),
    width: RfW(32),
    borderRadius: RfH(16),
    justifyContent: "center",
  },
  postcontainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  namesty: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.black,
    paddingHorizontal: RfW(10),
    lineHeight: RfH(17),
    fontFamily: "Poppins-Medium",
  },
  timesty: {
    fontSize: 11,
    fontWeight: "400",
    color: colors.DARK_GRAY,
    paddingHorizontal: RfW(10),
    lineHeight: RfH(14),
    fontFamily: "Poppins-Medium",
  },
  followcontainer: { flexDirection: "row" },
  followBtn: {
    width: RfW(77),
    height: RfH(22),
    borderWidth: 1,
    borderColor: colors.black,
    borderRadius: RfH(7),
    justifyContent: "center",
    marginHorizontal: RfW(20),
    marginTop: RfH(2),
  },
  followedBtn: {
    backgroundColor: colors.skyblue,
    borderColor: "#7966FF",
  },
  followtxt: {
    alignSelf: "center",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.black,
    fontFamily: "Poppins-Regular",
    top: RfH(1),
  },
  msgtextsty: {
    marginTop: RfH(10),
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.black,
    fontFamily: "Poppins-Regular",
    left: RfW(2),
  },
  massagepostcontainer: {
    borderWidth: 1,
    padding: RfH(10),
    borderRadius: RfH(7),
    borderColor: colors.LIGHT_BLACK,
    marginVertical: RfH(8),
    width: RfW(337),
    alignSelf: "center",
  },
  othercontainer: { flexDirection: "row" },
  postimgsty: {
    width: "100%",
    height: "100%",
    borderRadius: RfH(8),
    marginVertical: RfH(10),
    alignSelf: "center",
    resizeMode: "contain",
  },

  // Video hbhabha
  tabVideo: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    backgroundColor: colors.shadwo_blue,
    borderRadius: RfH(8),
    marginVertical: RfH(10),
    // width:RfW(315),
    padding: RfH(8),
  },
  playButton: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    width: RfW(50),
    height: RfH(50),
    borderRadius: 25,
  },
  clearButton: {},
  video: {},
  bottombtncon: {
    flexDirection: "row",
    backgroundColor: colors.shadwo_blue,
    borderRadius: 10,
    paddingHorizontal: RfW(10),
    paddingVertical: RfH(10),
  },
  btntxt: {
    fontSize: 14,
    color: colors.black,
    fontFamily: "Poppins-Medium",
    top: RfH(2),
  },
  disbtntxt: {
    fontSize: 11,
    fontFamily: "Poppins-Regular",
    color: colors.DARK_GRAY,
    top:RfH(2)
    // bottom: RfH(3),
  },
  loadingContainer: {
    alignSelf: "center",
    justifyContent: "center",
    flex: 1,
  },
  msgbtn: {
    backgroundColor: colors.shadwo_blue,
    width: RfW(80),
    height: RfH(30),
    justifyContent: "center",
    borderRadius: 5,
    // right: RfW(20),
    left: 20,
    alignSelf: "flex-end",
  },
  followbtn: {
    backgroundColor: colors.shadwo_blue,
    width: RfW(80),
    height: RfH(30),
    justifyContent: "center",
    borderRadius: 5,
    alignSelf: "center",
    left: RfW(6),
  },
  imageindexsty: {
    alignItems: "center",
    position: "absolute",
    alignSelf: "flex-end",
    top: RfH(55),
    right: RfW(10),
    marginTop: RfH(20),
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    height: RfH(25),
    width: RfW(40),
    justifyContent: "center",
    borderRadius: 5,
  },
  indextxtsty: {
    fontSize: 15,
    color: colors.WHITE,
    alignSelf: "center",
    justifyContent: "center",
  },
});
