import {StyleSheet} from 'react-native';
import {RfH, RfW} from '../../../utils/helper';
import {colors} from '../../../utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  phoneInputContainer: {
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 5,
    marginTop: RfH(20),
    height: RfH(55),
    backgroundColor: 'red',
  },
  phoneInputTextContainer: {
    left: RfW(-15),
  },
  inputfieldsty: {
    marginVertical: RfH(5),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: RfH(10),
    paddingHorizontal: RfW(5),
    backgroundColor: colors.LIGHT_GRAY,
    width: RfW(335),
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    marginBottom: RfH(10),
    fontFamily: 'Poppins-Regular',
  },
  txtcon: {
    marginTop: RfH(5),
  },
  phoneInputText: {
    fontSize: 16,
    position: 'absolute',
    bottom: 0,
  },
  imgsty: {
    height: RfH(100),
    width: RfW(100),
    borderRadius: RfH(10),
  },
  txt1: {
    fontSize: 20,
    fontWeight: '500',
    color: '#242424',
    fontFamily: 'Poppins-Medium',
    // alignSelf: 'center',
  },
  btnsty: {
    // position: 'absolute',
    // bottom: 20,
    height: RfH(50),
    alignSelf: 'center',
    justifyContent: 'center',
    width: RfW(335),
    borderRadius: RfH(10),
    backgroundColor: '#7966FF',
    marginVertical: RfH(20),
  },
  btntxtsty: {
    alignSelf: 'center',
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
  },
  placeholderheader: {
    fontSize: 16,
    fontWeight: '500',
    color: '#242424',
    left: RfH(2),
    marginVertical: RfH(5),
    top: RfH(5),
    fontFamily: 'Poppins-Medium',
  },
  dobtxt: {
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Poppins-Regular',
    left: RfW(5),
  },
  dobsampletxt: {
    fontSize: 13,
    color: colors.DARK_GRAY,
    // fontWeight:'400',
    fontFamily: 'Poppins-Regular',
    left: RfW(5),
  },
  txt2: {
    fontSize: 15,
    // fontWeight: '400',
    color: '#242424',
    opacity: 0.6,
    lineHeight: 22.5,
    fontFamily: 'Poppins-Medium',
  },
  imgcontainer: {
    marginTop: RfH(20),
    alignSelf: 'center',
  },
  phoneinputcon: {
    marginTop: RfH(15),
    // height: RfH(200),
    alignSelf: 'center',
    borderRadius: RfH(10),
    // elevation: 5,
  },
  txtcontainer: {marginTop: RfH(30), marginLeft: RfW(20)},
  msgtxtsty: {alignSelf: 'center', marginTop: RfH(20), flexDirection: 'row'},
  msgsty: {fontSize: 16, fontWeight: '500', color: 'gray'},
  msgsty2: {fontSize: 16, fontWeight: '500', color: 'blue'},
  pickerContainer: {
    marginVertical: RfH(5),
    marginBottom: RfH(15),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: RfH(10),
    paddingHorizontal: RfW(5),
    backgroundColor: colors.LIGHT_GRAY,
    width: RfW(335),
  },
  errorText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'red',
    left: RfW(5),
  },

  // Edit ProfileScreen Styles is Here

  editprocontainer: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  imgsty: {
    height: RfH(100),
    width: RfW(100),
    alignSelf: 'center',
  },
  imgcontainer: {
    borderWidth: 2,
    height: RfH(82),
    width: RfW(82),
    borderRadius: RfH(42),
    borderColor: colors.skyblue,
    justifyContent: 'center',
  },
  homecontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: RfW(20),
    marginTop: RfH(30),
  },
  txtsty: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.skyblue,
    fontFamily: 'Poppins-Regular',
    alignSelf: 'center',
    top: RfH(5),
  },
  probtn: {
    height: RfH(40),
    justifyContent: 'center',
    paddingHorizontal: RfW(20),
    alignSelf: 'center',
    flexDirection: 'row',
    right: RfW(5),
    borderBottomWidth: 1,
    borderBottomColor: colors.skyblue,
    marginTop: RfH(60),
  },
  profiletxt: {
    paddingVertical: RfH(10),
    paddingHorizontal: RfW(5),
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
  },
  namecon: {
    width: RfW(165),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: RfH(10),
    paddingHorizontal: RfW(5),
    backgroundColor: colors.LIGHT_GRAY,
  },
  profileimgsty: {
    height: 100,
    width: 100,
    borderRadius: RfH(50),
    borderColor: colors.skyblue,
    borderWidth: 1,
    alignSelf: 'center',
    marginTop: '10%',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  icontainer: {
    alignSelf: 'center',
    left: RfW(27),
    borderWidth: 1,
    bottom: RfH(19),
    borderRadius: RfH(10),
    height: RfH(20),
    width: RfW(20),
    justifyContent: 'center',
    borderColor: colors.skyblue,
  },
  updatebtn: {
    backgroundColor: '#7966FF',
    height: RfH(45),
    width: '90%',
    alignSelf: 'center',
    borderRadius: RfH(10),
    marginVertical: RfH(20),
    justifyContent: 'center',
  },
  updatetxt: {
    alignSelf: 'center',
    color: colors.WHITE,
    fontFamily: 'Poppins-Medium',
  },
  camponytxtsty: {
    color: '#242424',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBoldItalic',
  },
  datatxtsty: {
    color: colors.DARK_GRAY,
    fontSize: 13,
  },
  disctxtsty: {
    color: colors.DARK_GRAY,
    fontSize: 12,
  },
  separator: {
    height: 1,
    width: '100%',
    backgroundColor: colors.primary_black,
    opacity: 0.2,
    alignSelf: 'center',
    marginVertical: RfH(10),
  },
  plushiconsty: {
    height: RfH(21),
    width: RfW(20),
    top: RfH(10),
  },
  iconcontainer: {
    justifyContent: 'center',
    alignSelf: 'center',
    paddingVertical: RfH(2),
    marginHorizontal: RfW(5),
    borderBottomWidth: 1,
    width: RfW(25),
  },

  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 16,
    color: colors.black,
    fontFamily: 'Poppins-Regular',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    width: '45%',
  },
  buttonClose: {
    backgroundColor: colors.skyblue,
  },
  buttonRemove: {
    backgroundColor: 'red',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
