import {StyleSheet} from 'react-native';
import {RfH, RfW} from '../../../utils/helper';
import {colors} from '../../../utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  imgcontainer: {
    marginTop: RfH(50),
    alignSelf: 'center',
  },
  imgsty: {
    height: RfH(100),
    width: RfW(100),
  },
  inputfildsty: {
    // marginVertical: RfH(5),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: RfH(10),
    paddingHorizontal: RfW(5),
    backgroundColor: colors.LIGHT_GRAY,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: RfW(335),
  },
  placeholderheader: {
    fontSize: 15,
    // fontWeight: '500',
    color: '#242424',
    left: RfH(2),
    fontFamily: 'Poppins-Medium',
  },
  otpfieldtcon: {
    marginTop: RfH(10),
    height: RfH(180),
    alignSelf: 'center',
    // paddingHorizontal: RfW(15),
  },
  txtcon: {
    marginTop: RfH(10),
  },
  txt2: {
    fontSize: 14,
    alignSelf: 'center',
    fontWeight: '400',
    color: '#242424',
    opacity: 0.5,
    lineHeight: 22.5,
    fontFamily: 'Poppins-Medium',
  },
  btntxtsty: {
    alignSelf: 'center',
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
  },
  btnsty: {
    // position: 'absolute',
    bottom: RfH(60),
    height: RfH(50),
    alignSelf: 'center',
    justifyContent: 'center',
    width: '90%',
    borderRadius: RfH(25),
    backgroundColor: '#7966FF',
  },
  txtcontainer: {alignSelf: 'center', marginTop: RfH(30)},
  txt1: {
    fontSize: 18,
    fontWeight: '500',
    color: '#242424',
    alignSelf: 'center',
    fontFamily: 'Poppins-Medium',
  },
  input: {
    width: '15%',
    height: RfH(45),
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: RfH(5),
    paddingHorizontal: RfW(10),
    marginHorizontal: RfW(5),
    textAlign: 'center',
    fontSize: 20,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginTop: RfH(20),
    alignSelf: 'center',
  },
  inputfildstys: {
    marginTop: RfH(5),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: RfH(10),
    paddingHorizontal: RfW(5),
    backgroundColor: colors.LIGHT_GRAY,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: RfW(335),
  },
  btnsty: {
    height: RfH(50),
    alignSelf: 'center',
    justifyContent: 'center',
    width: RfW(335),
    borderRadius: RfH(10),
    backgroundColor: '#7966FF',
    marginTop: RfH(60),
  },
  btntxtsty: {
    alignSelf: 'center',
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
  },
});
